apiVersion: v1
kind: Namespace
metadata:
  name: sashiko
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sashiko-ksa
  namespace: sashiko
  annotations:
    iam.gke.io/gcp-service-account: sashiko-app@GCP_PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sashiko-data-pvc
  namespace: sashiko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sashiko-deployment
  namespace: sashiko
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sashiko
  template:
    metadata:
      labels:
        app: sashiko
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: n2d-pool
      securityContext:
        fsGroup: 1000
      serviceAccountName: sashiko-ksa
      terminationGracePeriodSeconds: 120
      containers:
        - name: sashiko
          image: us-docker.pkg.dev/GCP_PROJECT_ID/sashiko-repository/sashiko:next
          command: ["/bin/bash", "/usr/local/bin/docker-entrypoint.sh"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "24"
              memory: "105Gi"
            limits:
              cpu: "30"
              memory: "115Gi"
          ports:
            - containerPort: 8080
          env:
            - name: SASHIKO_LOG_PLAIN
              value: "true"
            - name: NO_COLOR
              value: "true"
            - name: SASHIKO__DATABASE__URL
              value: "/data/db/sashiko.db"
            - name: SASHIKO__GIT__REPOSITORY_PATH
              value: "/app/third_party/linux"
            - name: SASHIKO__REVIEW__WORKTREE_DIR
              value: "/mnt/local-ssd/worktrees"
            - name: SASHIKO__SERVER__PORT
              value: "8080"
            - name: SASHIKO__AI__MODEL
              value: "gemini-3.1-pro-preview"
            - name: SASHIKO__AI__MAX_INTERACTIONS
              value: "100"
            - name: SASHIKO__MAILING_LISTS__TRACK
              value: >-
                bpf,cgroups,damon,dmaengine,dri-devel,driver-core,dwarves,fuse-devel,kvm,
                linux-bluetooth,linux-clk,linux-cifs,linux-ext4,linux-hwmon,linux-input,
                linux-kernel,linux-media,linux-mm,linux-nfs,linux-pci,linux-perf-users,linux-phy,
                linux-pwm,linux-rdma,linux-trace-kernel,linux-watchdog,mptcp,netdev,
                rust-for-linux,kvmarm,linux-arm-kernel,linux-block,linux-scsi,
                linux-crypto,linux-riscv,intel-gfx,intel-xe,linux-kselftest,
                kexec,linux-iio,netfilter-devel,linux-renesas-soc,linux-omap,linux-xfs,
                linux-cxl,nvdimm,linux-ide,linux-btrfs,rcu,sched-ext,oe-linux-nfc,
                batman,linux-s390,linux-devicetree,imx,linux-sunxi,linux-amlogic,
                live-patching,openvpn-devel,platform-driver-x86,linux-arm-msm,
                linux-modules,nouveau,nova-gpu,ntb,selinux,linux-raid,linux-rt,linux-rtc,
                linux-can,linux-target,linux-hardening,linux-security-module,linux-unionfs,mfd,linux-leds,mhi,
                linux-mtd,audit,linux-integrity,linux-fscrypt,fsverity,ocfs2-devel
            - name: SASHIKO__REVIEW__CONCURRENCY
              value: "24"
            - name: SASHIKO__SMTP__SENDER_ADDRESS
              value: "sashiko-bot@kernel.org"
            - name: SASHIKO__SMTP__SERVER
              value: "mail.kernel.org"
            - name: SASHIKO__SMTP__PORT
              value: "465"
            - name: SASHIKO__SMTP__USERNAME
              value: "sashiko-bot@kernel.org"
            - name: SASHIKO__SMTP__REPLY_TO
              value: "sashiko-reviews@lists.linux.dev"
            - name: SASHIKO__SMTP__DRY_RUN
              value: "false"
            - name: SASHIKO__REVIEW__EMAIL_POLICY_PATH
              value: "/app/email_policy.toml"
            - name: GIT_CONFIG_COUNT
              value: "1"
            - name: GIT_CONFIG_KEY_0
              value: "grep.threads"
            - name: GIT_CONFIG_VALUE_0
              value: "1"
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sashiko-secrets
                  key: LLM_API_KEY
          args: ["--debug", "--track", "--download", "10"]
          volumeMounts:
            - name: sashiko-storage
              mountPath: /data
              subPath: data-dir
            - name: sashiko-storage
              mountPath: /app/third_party/linux
              subPath: linux-repo
            - name: fast-ssd
              mountPath: /mnt/local-ssd
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: sashiko-storage
          persistentVolumeClaim:
            claimName: sashiko-data-pvc
        - name: fast-ssd
          hostPath:
            path: /mnt/disks/ssd0
            type: Directory
        - name: tmp-volume
          emptyDir: {}
